
const productos = [
    {
      id: 1,
      nombre: "Leche",
      producto: "Lácteo",
      marca: "Marca A",
      precio: 1500,
      perecible: true,
      descripcion: "Leche entera en envase de 1 litro",
    },
    {
      id: 2,
      nombre: "Pan",
      producto: "Panadería",
      marca: "Marca B",
      precio: 500,
      perecible: true,
      descripcion: "Pan de molde blanco en rebanadas",
    },
    {
      id: 3,
      nombre: "Arroz",
      producto: "Granos",
      marca: "Marca C",
      precio: 1200,
      perecible: false,
      descripcion: "Arroz blanco en paquete de 1 kg",
    },
    {
      id: 4,
      nombre: "Azúcar",
      producto: "Endulzante",
      marca: "Marca D",
      precio: 800,
      perecible: false,
      descripcion: "Azúcar blanca en paquete de 1 kg",
    },
    {
      id: 5,
      nombre: "Manzanas",
      producto: "Frutas",
      marca: "Marca E",
      precio: 1000,
      perecible: true,
      descripcion: "Manzanas rojas frescas, paquete de 6 unidades",
    },
    {
      id: 6,
      nombre: "Papas",
      producto: "Verduras",
      marca: "Marca F",
      precio: 700,
      perecible: true,
      descripcion: "Papas blancas en bolsa de 2 kg",
    },
    {
      id: 7,
      nombre: "Yogur",
      producto: "Lácteo",
      marca: "Marca G",
      precio: 900,
      perecible: true,
      descripcion: "Yogur natural en envase individual",
    },
    {
      id: 8,
      nombre: "Huevos",
      producto: "Huevos",
      marca: "Marca H",
      precio: 1800,
      perecible: true,
      descripcion: "Huevos frescos en cartón de 12 unidades",
    },
    {
      id: 9,
      nombre: "Pan de molde",
      producto: "Panadería",
      marca: "Marca I",
      precio: 1500,
      perecible: true,
      descripcion: "Pan de molde integral en rebanadas",
    },
    {
      id: 10,
      nombre: "Aceite de oliva",
      producto: "Aceite",
      marca: "Marca J",
      precio: 3500,
      perecible: false,
      descripcion: "Aceite de oliva extra virgen en botella de 500 ml",
    },
    {
      id: 11,
      nombre: "Fideos",
      producto: "Pasta",
      marca: "Marca K",
      precio: 600,
      perecible: false,
      descripcion: "Fideos de trigo en paquete de 500 g",
    },
    {
      id: 12,
      nombre: "Jugo de naranja",
      producto: "Bebida",
      marca: "Marca L",
      precio: 1200,
      perecible: true,
      descripcion: "Jugo de naranja natural en envase de 1 litro",
    },
    {
      id: 13,
      nombre: "Atún en lata",
      producto: "Conserva",
      marca: "Marca M",
      precio: 2500,
      perecible: false,
      descripcion: "Atún en aceite vegetal en lata de 200 g",
    },
    {
      id: 14,
      nombre: "Mermelada de frutilla",
      producto: "Mermelada",
      marca: "Marca N",
      precio: 2000,
      perecible: false,
      descripcion: "Mermelada de frutilla en frasco de 250 g",
    },
    {
      id: 15,
      nombre: "Pechugas de pollo",
      producto: "Carnes",
      marca: "Marca O",
      precio: 4500,
      perecible: true,
      descripcion: "Pechugas de pollo en bandeja de 500 g",
    },
    {
      id: 16,
      nombre: "Mantequilla",
      producto: "Lácteo",
      marca: "Marca P",
      precio: 2000,
      perecible: true,
      descripcion: "Mantequilla sin sal en barra de 200 g",
    },
    {
      id: 17,
      nombre: "Queso Cheddar",
      producto: "Queso",
      marca: "Marca Q",
      precio: 3000,
      perecible: true,
      descripcion: "Queso Cheddar en rebanadas",
    },
    {
      id: 18,
      nombre: "Café",
      producto: "Bebida",
      marca: "Marca R",
      precio: 4000,
      perecible: false,
      descripcion: "Café molido 100% arabica en paquete de 250 g",
    },
    {
      id: 19,
      nombre: "Galletas",
      producto: "Snack",
      marca: "Marca S",
      precio: 1500,
      perecible: false,
      descripcion: "Galletas integrales sabor chocolate en paquete de 200 g",
    },
    {
      id: 20,
      nombre: "Pasta de dientes",
      producto: "Higiene personal",
      marca: "Marca T",
      precio: 2000,
      perecible: false,
      descripcion: "Pasta de dientes con fluor en tubo de 100 g",
    },
    {
      id: 21,
      nombre: "Sal",
      producto: "Condimento",
      marca: "Marca U",
      precio: 500,
      perecible: false,
      descripcion: "Sal de mar fina en paquete de 500 g",
    },
    {
      id: 22,
      nombre: "Yogur de frutas",
      producto: "Lácteo",
      marca: "Marca V",
      precio: 700,
      perecible: true,
      descripcion: "Yogur de frutas variadas en envase individual",
    },
    {
      id: 23,
      nombre: "Papel higiénico",
      producto: "Higiene personal",
      marca: "Marca W",
      precio: 2500,
      perecible: false,
      descripcion: "Rollo de papel higiénico suave, paquete de 4 unidades",
    },
    {
      id: 24,
      nombre: "Mango",
      producto: "Frutas",
      marca: "Marca X",
      precio: 1500,
      perecible: true,
      descripcion: "Mango maduro, unidad",
    },
    {
      id: 25,
      nombre: "Cereal de desayuno",
      producto: "Cereales",
      marca: "Marca Y",
      precio: 3500,
      perecible: false,
      descripcion: "Cereal de hojuelas de maíz en caja de 500 g",
    },
    {
      id: 26,
      nombre: "Queso Parmesano",
      producto: "Queso",
      marca: "Marca Z",
      precio: 2800,
      perecible: true,
      descripcion: "Queso Parmesano rallado en frasco de 100 g",
    },
    {
      id: 27,
      nombre: "Jabón de Lavandería",
      producto: "Limpieza",
      marca: "Marca AA",
      precio: 1200,
      perecible: false,
      descripcion: "Jabón en barra para lavar ropa, paquete de 200 g",
    },
    {
      id: 28,
      nombre: "Pasta Dental",
      producto: "Higiene bucal",
      marca: "Marca BB",
      precio: 1500,
      perecible: false,
      descripcion: "Pasta dental con flúor y blanqueadora, tubo de 100 g",
    },
    {
      id: 29,
      nombre: "Mantequilla de Maní",
      producto: "Untable",
      marca: "Marca CC",
      precio: 2000,
      perecible: true,
      descripcion: "Mantequilla de maní natural, frasco de 250 g",
    },
    {
      id: 30,
      nombre: "Cerveza",
      producto: "Bebida alcohólica",
      marca: "Marca DD",
      precio: 1500,
      perecible: true,
      descripcion: "Cerveza Lager en lata de 355 ml",
    },
    {
      id: 31,
      nombre: "Pasta de Tomate",
      producto: "Conserva",
      marca: "Marca EE",
      precio: 800,
      perecible: false,
      descripcion: "Pasta de tomate en lata de 200 g",
    },
    {
      id: 32,
      nombre: "Café Instantáneo",
      producto: "Bebida",
      marca: "Marca FF",
      precio: 2500,
      perecible: false,
      descripcion: "Café instantáneo en frasco de 200 g",
    },
    {
      id: 33,
      nombre: "Pasta de Té",
      producto: "Infusión",
      marca: "Marca GG",
      precio: 1000,
      perecible: false,
      descripcion: "Pasta de té negro en caja de 100 unidades",
    },
    {
      id: 34,
      nombre: "Galletas de Avena",
      producto: "Snack",
      marca: "Marca HH",
      precio: 1200,
      perecible: false,
      descripcion: "Galletas de avena y pasas en paquete de 200 g",
    },
    {
      id: 35,
      nombre: "Aceite Vegetal",
      producto: "Aceite",
      marca: "Marca II",
      precio: 1800,
      perecible: false,
      descripcion: "Aceite vegetal de girasol en botella de 1 litro",
    },
    {
      id: 36,
      nombre: "Yogur Griego",
      producto: "Lácteo",
      marca: "Marca JJ",
      precio: 1200,
      perecible: true,
      descripcion: "Yogur griego natural en envase individual",
    },
    {
      id: 37,
      nombre: "Cereal de Maíz",
      producto: "Cereales",
      marca: "Marca KK",
      precio: 2200,
      perecible: false,
      descripcion: "Cereal de maíz azucarado en caja de 400 g",
    },
    {
      id: 38,
      nombre: "Aceitunas",
      producto: "Conserva",
      marca: "Marca LL",
      precio: 1500,
      perecible: true,
      descripcion: "Aceitunas verdes sin hueso en frasco de 200 g",
    },
    {
      id: 39,
      nombre: "Miel",
      producto: "Endulzante",
      marca: "Marca MM",
      precio: 2500,
      perecible: false,
      descripcion: "Miel pura en frasco de 500 g",
    },
    {
      id: 40,
      nombre: "Jamón",
      producto: "Embutidos",
      marca: "Marca NN",
      precio: 3500,
      perecible: true,
      descripcion: "Jamón cocido en lonjas, paquete de 200 g",
    },
    {
      id: 41,
      nombre: "Crema de Manos",
      producto: "Cuidado personal",
      marca: "Marca OO",
      precio: 2000,
      perecible: false,
      descripcion: "Crema de manos hidratante, tubo de 100 ml",
    },
    {
      id: 42,
      nombre: "Pasta de Guayaba",
      producto: "Mermelada",
      marca: "Marca PP",
      precio: 1800,
      perecible: false,
      descripcion: "Pasta de guayaba en frasco de 300 g",
    },
    {
      id: 43,
      nombre: "Cebolla",
      producto: "Verduras",
      marca: "Marca QQ",
      precio: 800,
      perecible: true,
      descripcion: "Cebolla morada, unidad",
    },
    {
      id: 44,
      nombre: "Salsa de Soja",
      producto: "Salsas",
      marca: "Marca RR",
      precio: 1000,
      perecible: true,
      descripcion: "Salsa de soja en botella de 250 ml",
    },
    {
      id: 45,
      nombre: "Cerveza Artesanal",
      producto: "Bebida alcohólica",
      marca: "Marca SS",
      precio: 4000,
      perecible: true,
      descripcion: "Cerveza artesanal IPA en botella de 500 ml",
    },
    {
      id: 46,
      nombre: "Sopa Instantánea",
      producto: "Alimentos instantáneos",
      marca: "Marca TT",
      precio: 1500,
      perecible: false,
      descripcion: "Sopa instantánea de pollo en sobre de 50 g",
    },
    {
      id: 47,
      nombre: "Galletas de Arroz",
      producto: "Snack",
      marca: "Marca UU",
      precio: 1300,
      perecible: false,
      descripcion: "Galletas de arroz integral en paquete de 150 g",
    },
    {
      id: 48,
      nombre: "Vino Tinto",
      producto: "Bebida alcohólica",
      marca: "Marca VV",
      precio: 5000,
      perecible: true,
      descripcion: "Vino tinto reserva en botella de 750 ml",
    },
    {
      id: 49,
      nombre: "Champú",
      producto: "Cuidado capilar",
      marca: "Marca WW",
      precio: 2500,
      perecible: false,
      descripcion: "Champú revitalizante, botella de 400 ml",
    },
    {
      id: 50,
      nombre: "Tomate en Lata",
      producto: "Conserva",
      marca: "Marca XX",
      precio: 1200,
      perecible: false,
      descripcion: "Tomate pelado en lata de 400 g",
    },
  ];
  
export default productos;
  